### ISSUE TITLE
Support for ASIC 80 chip G-Blade correct hashrate

### ISSUE THREAD

**Issue by jmordica** [dtbartle/cgminer-gc3355#11]
As shown here http://cryptomining-blog.com/1893-performance-results-of-the-new-gridseed-blade-miner-asic/ the local hashrate doesn't get displayed correctly in the screen session.

Can you add support to show correct hash rate for these units?

**Comment by dtbartle** [comment]
AFAIK the bfgminer support was based on my patch, so you might be able to see what they're doing differently in code.

**Comment by dtbartle** [comment]
I pushed a change to increase the maximum number of gridseed chips to 256 (that ought to be enough for anybody). You can try adding chips=40 to --gridseed-options.
