### ISSUE TITLE
Add args to cgminer config file

### ISSUE THREAD

**Issue by jmordica** [dtbartle/cgminer-gc3355#2]
I tried adding freq to the config file but cgminer didn't start with the clock speed I set "850". Also, adding hotplug didn't work either. It seems cgminer is ignoring these.

**Comment by dtbartle** [comment]
My config has the following:
"gridseed-options" : "freq=850",
"hotplug" : "5",

**Comment by jmordica** [comment]
Ok thanks I was adding it in the config wrong. Another issue (related) is that whenever you send an APi request to Write Config to cgminer, it doesn't write these gridseed-options in the config. So if I want to change the pool URL, I can do so while it's running fine but if cgminer gets restarted and uses the config, since the freq, voltage, etc.. isn't written to the config by cgminer, it starts without these gridseed-options.

**Comment by dtbartle** [comment]
Fixed the config writing issue.
